#   gem 'sqlite3'
#   gem 'pg'
#
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  #port: 5432
  database: postgres://rpanubutaktagl:21338ea0b62194b00fb38f59d9ea05f1c25b667d2ecf1070593ea3f89e1cdb0c@ec2-23-23-78-213.compute-1.amazonaws.com:5432/de0v0f3jtune1d
  pool: 5
  username: ror
  password:
